# Generated by Django 5.1.5 on 2025-02-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nitrogen_min', models.FloatField()),
                ('nitrogen_max', models.FloatField()),
                ('phosphorus_min', models.FloatField()),
                ('phosphorus_max', models.FloatField()),
                ('potassium_min', models.FloatField()),
                ('potassium_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('soil_type', models.CharField(max_length=15)),
                ('moisture_content', models.CharField(choices=[('high', 'High'), ('moderate-high', 'Moderate-High'), ('moderate', 'Moderate'), ('moderate-low', 'Moderate-Low'), ('low', 'Low')], default='moderate', max_length=20)),
                ('salinity', models.CharField(choices=[('high', 'High'), ('moderate-high', 'Moderate-High'), ('moderate', 'Moderate'), ('moderate-low', 'Moderate-Low'), ('low', 'Low')], default='moderate', max_length=20)),
            ],
        ),
    ]
