# Generated by Django 5.1.5 on 2025-02-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('peaty', 'Peaty'), ('saline', 'Saline'), ('silty', 'Silty')], max_length=15),
        ),
    ]
